-- 1. Tabla mal diseñada
CREATE TABLE ventas_bad ( ... );

-- Inserts
INSERT INTO ventas_bad ...

-- 2. Normalización
CREATE TABLE clientes ...
CREATE TABLE productos ...
CREATE TABLE ventas ...
CREATE TABLE ventas_detalle ...

-- 3. Desnormalización
CREATE MATERIALIZED VIEW ventas_por_dia ...
